import { Vehicle, Booking } from '../types';

export const initialMockVehicles: Vehicle[] = [
  {
    _id: 'veh_rr_spectre',
    name: 'Rolls-Royce Spectre',
    brand: 'Rolls-Royce',
    category: 'Luxury',
    tagline: 'The Ultra-Luxury All-Electric Super Coupé',
    taglineAr: 'الكوبيه الفاخرة الكهربائية الأرقى في العالم',
    year: 2025,
    pricePerDay: 4800,
    weeklyDiscount: 15,
    deposit: 8000,
    currency: 'SAR',
    transmission: 'Automatic Dual-Drive',
    fuelType: 'All-Electric Ultra-Quiet',
    seats: 4,
    doors: 2,
    acceleration: '4.5s (0-100 km/h)',
    topSpeed: '250 km/h',
    horsepower: '584 HP',
    engine: 'Dual Synchronous Electric Motors',
    color: 'Chartreuse & Black Diamond Two-Tone',
    available: true,
    featured: true,
    rating: 4.98,
    reviewCount: 28,
    mileageLimitPerDay: 250,
    extraMileageCost: 18,
    location: 'Riyadh - King Khalid International Airport (Terminal 1-5 VIP)',
    images: [
      'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      'Starlight Headliner with 4,796 Hand-Placed Fibre-Optic Stars',
      'Illuminated Spirit of Ecstasy & Pantheon Grille',
      'Planar Suspension System with Electronic Decoupling',
      'Bespoke 18-Speaker Audio Architecture (1,400W)',
      'Effortless Power-Assisted Coach Doors',
      'Whisper-Quiet Acoustic Glazing Cabin'
    ],
    featuresAr: [
      'سقف النجوم المضاء بـ 4,796 نقطة ألياف ضوئية متلألئة',
      'تمثال روح النشوة وشبك البانثيون المضيء بتقنية LED',
      'نظام تعليق بلانار فائق النعومة مع فصل إلكتروني',
      'نظام صوتي بيسبوك فاخر بقوة 1,400 واط بـ 18 مكبراً',
      'أبواب كوتش تفتح وتغلق كهربائياً بلمسة زر',
      'عزل صوتي فائق الهدوء مع زجاج مزدوج مقوّى'
    ]
  },
  {
    _id: 'veh_porsche_911gt3',
    name: 'Porsche 911 GT3 RS',
    brand: 'Porsche',
    category: 'Sports',
    tagline: 'Aerodynamic Perfection & High-Revving Racing Precision',
    taglineAr: 'قمة الهندسة الديناميكية الهوائية والأداء الحلباتي الخارق',
    year: 2025,
    pricePerDay: 3900,
    weeklyDiscount: 12,
    deposit: 6000,
    currency: 'SAR',
    transmission: '7-Speed Dual-Clutch PDK',
    fuelType: 'Super 98 Premium Petrol',
    seats: 2,
    doors: 2,
    acceleration: '3.2s (0-100 km/h)',
    topSpeed: '296 km/h',
    horsepower: '525 HP',
    engine: '4.0L Naturally Aspirated Boxer-6 (9,000 RPM)',
    color: 'Arctic Grey with Acid Accent Carbon',
    available: true,
    featured: true,
    rating: 4.96,
    reviewCount: 42,
    mileageLimitPerDay: 200,
    extraMileageCost: 15,
    location: 'Riyadh - Al Olaya Prestige Showroom',
    images: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      'Active Drag Reduction System (DRS) Active Aero Wing',
      'Porsche Ceramic Composite Brakes (PCCB)',
      'Full Carbon Fiber Bucket Seats & Lightweight Rollcage',
      'Chrono Package with Precision Lap Trigger',
      'Multi-stage PASM & PTV Plus Torque Vectoring',
      'Titanium Sports Exhaust System with Valve Control'
    ],
    featuresAr: [
      'جناح خلفي هوائي نشط مع نظام تخفيض السحب DRS',
      'مكابح بورشه السيراميكية المركبة فائقة القوة PCCB',
      'مقاعد باكت رياضية بالكامل من ألياف الكربون الخفيف',
      'باقة كرونو الرياضية مع مؤقت حلبات دقيق',
      'نظام توجيه العزم والتعليق المتكيف PASM & PTV Plus',
      'عادم رياضي من التيتانيوم بصوت زئير طبيعي حماسي'
    ]
  },
  {
    _id: 'veh_maybach_s680',
    name: 'Mercedes-Maybach S 680',
    brand: 'Mercedes-Benz',
    category: 'Executive',
    tagline: 'Unrivaled First-Class Luxury & V12 Majesty',
    taglineAr: 'فخامة الدرجة الأولى الملكية بمحرك V12 الأسطوري',
    year: 2025,
    pricePerDay: 4200,
    weeklyDiscount: 15,
    deposit: 7000,
    currency: 'SAR',
    transmission: '9G-TRONIC Automatic',
    fuelType: 'Premium Petrol',
    seats: 4,
    doors: 4,
    acceleration: '4.5s (0-100 km/h)',
    topSpeed: '250 km/h',
    horsepower: '621 HP',
    engine: '6.0L Twin-Turbocharged V12 Biturbo',
    color: 'Onyx Black & Selenite Grey Duo-Tone',
    available: true,
    featured: true,
    rating: 4.99,
    reviewCount: 35,
    mileageLimitPerDay: 250,
    extraMileageCost: 16,
    location: 'Jeddah - North Corniche Waterfront Hub',
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      'Executive First-Class Rear Lounge with Calf Massage & Recline',
      'Burmester High-End 4D Surround Sound (31 Speakers, 1,750W)',
      'Active Road Noise Compensation & Soft-Close Panoramic Roof',
      'Silver-Plated Champagne Flutes & Refrigerated Compartment',
      'E-ACTIVE BODY CONTROL Predictive Hydro-Pneumatic Suspension',
      'Chauffeur Package with Footrest Extension'
    ],
    featuresAr: [
      'جناح خلفي فاخر من الدرجة الأولى مع تدليك الساقين وانحناء كامل',
      'نظام بورميستر الصوتي رباعي الأبعاد بـ 31 مكبراً وقوة 1,750 واط',
      'نظام نشط لعزل ضوضاء الطريق وسقف بانورامي معتم إلكترونياً',
      'كؤوس شمبانيا مطلية بالفضة مع ثلاجة تبريد مدمجة',
      'نظام تعليق E-ACTIVE التنبؤي لمسح الطريق وامتصاص المطبات',
      'باقة السائق الخاص مع دعامة ممتدة للقدمين وراحة مطلقة'
    ]
  },
  {
    _id: 'veh_lambo_urus',
    name: 'Lamborghini Urus Performante',
    brand: 'Lamborghini',
    category: 'SUV',
    tagline: 'The Ultimate Super Sports Utility Masterpiece',
    taglineAr: 'أقوى وأشرس سيارة دفع رباعي فائقة الأداء في العالم',
    year: 2025,
    pricePerDay: 4400,
    weeklyDiscount: 10,
    deposit: 7500,
    currency: 'SAR',
    transmission: '8-Speed Automatic All-Wheel Drive',
    fuelType: 'Super 98 Premium Petrol',
    seats: 5,
    doors: 5,
    acceleration: '3.3s (0-100 km/h)',
    topSpeed: '306 km/h',
    horsepower: '666 HP',
    engine: '4.0L Twin-Turbocharged V8 with Rally Mode',
    color: 'Giallo Inti Lemon Yellow & Naked Carbon',
    available: true,
    featured: true,
    rating: 4.97,
    reviewCount: 51,
    mileageLimitPerDay: 200,
    extraMileageCost: 18,
    location: 'AlUla - Banyan Tree & Desert Resort Pavilion',
    images: [
      'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      'Carbon Fiber Bonnet, Roof, and Aerodynamic Rear Spoiler',
      'Akrapovič Titanium Lightweight Quad Sport Exhaust',
      'Rally Drive Mode for High-Speed Loose Surface Drifting',
      'Carbon Ceramic Brakes with Giallo Brake Calipers',
      '23-inch Forged Pelope Diamond-Cut Alloys with Trofeo R Tyres',
      'Alcantara Sport Seats with Contrast Hexagonal Stitching'
    ],
    featuresAr: [
      'غطاء محرك وسقف وجناح هوائي خلفي بالكامل من ألياف الكربون',
      'نظام عادم أكرابوفيتش تيتانيوم رباعي المخرج بصوت جهوري مذهل',
      'وضع قيادة الرالي المخصص للانجرافات السريعة على المسارات الرملية',
      'مكابح كربون سيراميكية مع كليبرات رياضية صفراء مخصصة',
      'جنوط بيسكوك قياس 23 إنش مع إطارات تروفيو آر عالية التماسك',
      'مقصورة ألكانتارا فاخرة بتطريزات سداسية متقنة وألياف الكربون'
    ]
  },
  {
    _id: 'veh_lucid_sapphire',
    name: 'Lucid Air Sapphire',
    brand: 'Lucid Motors',
    category: 'Luxury',
    tagline: '1,234 Horsepower Sub-2-Second Electric Dominance',
    taglineAr: 'هندسة المستقبل بقوة 1,234 حصاناً وتسارع يكسر حاجز الثانيتين',
    year: 2025,
    pricePerDay: 3700,
    weeklyDiscount: 14,
    deposit: 5500,
    currency: 'SAR',
    transmission: 'Tri-Motor AWD with Torque Vectoring',
    fuelType: 'Ultra-High Voltage 900V Electric Architecture',
    seats: 5,
    doors: 4,
    acceleration: '1.89s (0-100 km/h)',
    topSpeed: '330 km/h',
    horsepower: '1,234 HP',
    engine: 'Tri-Motor In-House Electric Powertrain',
    color: 'Sapphire Midnight Blue Metallic',
    available: true,
    featured: true,
    rating: 4.95,
    reviewCount: 19,
    mileageLimitPerDay: 300,
    extraMileageCost: 12,
    location: 'Riyadh - King Khalid International Airport (Terminal 1-5 VIP)',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      '34-Inch Curved Glass Cockpit 5K Display',
      'Carbon Ceramic Brakes with 10-Piston Calipers',
      'Sapphire Themed Adaptive 18-Way Bolstered Sport Seats',
      'Surreal Sound Pro 21-Speaker Immersive Spatial Audio',
      'DreamDrive Pro Advanced Autonomous Driver Assistance',
      'Over 700 km Real-World Electric Range per Charge'
    ],
    featuresAr: [
      'شاشة قمرة القيادة الزجاجية المنحنية بدقة 5K قياس 34 إنش',
      'مكابح كربون سيراميكية بـ 10 مكابس لقوة توقف فائقة الثبات',
      'مقاعد رياضية متكيفة بـ 18 وضعية مخصصة للتحكم التام',
      'نظام صوتي سريالي محيطي بـ 21 مكبراً وتوزيع صوتي مكاني',
      'نظام دريم درايف برو للقيادة الذاتية والمساعدة المتقدمة',
      'مدى سير كهربائي يتجاوز 700 كم بالشحنة الواحدة الفائقة'
    ]
  },
  {
    _id: 'veh_range_rover_sv',
    name: 'Range Rover SV Long Wheelbase',
    brand: 'Land Rover',
    category: 'SUV',
    tagline: 'The Pinnacle of Aristocratic Luxury & Refined All-Terrain Capability',
    taglineAr: 'قمة الفخامة البريطانية الأرستقراطية وقوة الدفع الرباعي المطلقة',
    year: 2025,
    pricePerDay: 3600,
    weeklyDiscount: 15,
    deposit: 5500,
    currency: 'SAR',
    transmission: '8-Speed Electronic Automatic',
    fuelType: 'Twin-Turbocharged Petrol Mild Hybrid',
    seats: 4,
    doors: 5,
    acceleration: '4.4s (0-100 km/h)',
    topSpeed: '261 km/h',
    horsepower: '606 HP',
    engine: '4.4L Twin-Turbo V8 with All-Wheel Steering',
    color: 'Ionian Silver Satin with Corinthian Bronze Accents',
    available: true,
    featured: true,
    rating: 4.94,
    reviewCount: 31,
    mileageLimitPerDay: 250,
    extraMileageCost: 14,
    location: 'Riyadh - Al Olaya Prestige Showroom',
    images: [
      'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      'SV Signature Suite with Electrically Deployable Club Table',
      'Meridian Signature 35-Speaker Sound System (1,600W)',
      'Active Noise Cancellation Headrest Speakers',
      'Ceramic Controls and Bespoke Semi-Aniline Leather',
      'Integrated Champagne Refrigerator & Dartington Crystal',
      'Dynamic Air Suspension with Integrated Chassis Control'
    ],
    featuresAr: [
      'جناح إس في الموقّع مع طاولة ضيافة متحركة كهربائياً',
      'نظام ميريديان الصوتي المميز بـ 35 مكبراً بقوة 1,600 واط',
      'عوازل نشطة للضوضاء مدمجة في مساند الرأس',
      'مفاتيح تحكم خزفية يدوية الصنع وجلود أنيلين فاخرة',
      'ثلاجة كونسول مدمجة مع كؤوس كريستال دارتينغتون',
      'نظام تعليق هوائي ديناميكي مع تحكم متكامل بالشاسيه'
    ]
  },
  {
    _id: 'veh_ferrari_roma',
    name: 'Ferrari Roma Spider',
    brand: 'Ferrari',
    category: 'Sports',
    tagline: 'La Nuova Dolce Vita in an Open-Top V8 Italian Grand Tourer',
    taglineAr: 'أسلوب الحياة الإيطالية الساحرة في سيارة كشف بثماني أسطوانات',
    year: 2025,
    pricePerDay: 4600,
    weeklyDiscount: 10,
    deposit: 8000,
    currency: 'SAR',
    transmission: '8-Speed F1 Dual-Clutch',
    fuelType: 'Super 98 Premium Petrol',
    seats: 2,
    doors: 2,
    acceleration: '3.4s (0-100 km/h)',
    topSpeed: '320 km/h',
    horsepower: '620 HP',
    engine: '3.9L Twin-Turbocharged V8 (Award-Winning)',
    color: 'Rosso Corsa Red & Cuoio Leather Interior',
    available: true,
    featured: false,
    rating: 4.96,
    reviewCount: 22,
    mileageLimitPerDay: 200,
    extraMileageCost: 20,
    location: 'Jeddah - North Corniche Waterfront Hub',
    images: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      '5-Layer Bespoke Fabric Soft Top (Opens in 13.5s at up to 60 km/h)',
      'Side Slip Control 6.0 (SSC 6.0) with Ferrari Dynamic Enhancer',
      'Passenger Display 8.8-Inch Full HD Screen',
      'Dual Cockpit Concept with Full Digital Gauge Cluster',
      'Carbon Fiber Steering Wheel with LED Shift Lights',
      'Iconic Ferrari Sport Exhaust Soundtrack'
    ],
    featuresAr: [
      'سقف قماشي فاخر بـ 5 طبقات يفتح في 13.5 ثانية حتى سرعة 60 كم/س',
      'نظام التحكم بالانزلاق الجانبي SSC 6.0 مع معزز فيراري الديناميكي',
      'شاشة عرض للراكب الأمامي قياس 8.8 إنش بتقنية Full HD',
      'مقصورة مزدوجة مستوحاة من سيارات السباق مع شاشات رقمية بالكامل',
      'عجلة قيادة من ألياف الكربون مع مؤشرات تبديل سرعات LED',
      'صوت زئير محرك فيراري V8 الأسطوري الآسر'
    ]
  },
  {
    _id: 'veh_bmw_m8_comp',
    name: 'BMW M8 Competition Gran Coupé',
    brand: 'BMW',
    category: 'Executive',
    tagline: 'M Track Precision Blended with Four-Door Grand Touring Luxury',
    taglineAr: 'دقة مسارات السباقات مع راحة ورحابة سيارات الجران كوبيه الفاخرة',
    year: 2025,
    pricePerDay: 3200,
    weeklyDiscount: 15,
    deposit: 5000,
    currency: 'SAR',
    transmission: '8-Speed M Steptronic with Drivelogic',
    fuelType: 'Premium Petrol',
    seats: 5,
    doors: 4,
    acceleration: '3.2s (0-100 km/h)',
    topSpeed: '305 km/h',
    horsepower: '617 HP',
    engine: '4.4L M TwinPower Turbo V8 with M xDrive',
    color: 'Isle of Man Green Metallic with Merino Sakhir Orange',
    available: true,
    featured: false,
    rating: 4.93,
    reviewCount: 29,
    mileageLimitPerDay: 250,
    extraMileageCost: 12,
    location: 'Riyadh - Al Olaya Prestige Showroom',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1600&q=85'
    ],
    features: [
      'M xDrive All-Wheel Drive with 2WD Pure RWD Drift Mode',
      'Bowers & Wilkins Diamond Surround Sound System (1,400W)',
      'M Carbon Ceramic Brakes & M Carbon Exterior Package',
      'BMW Laserlight with Iconic Laser Glow',
      'Adaptive M Suspension Professional with Active Roll Stabilization',
      'M Sport Exhaust System with Quad Black Chrome Tips'
    ],
    featuresAr: [
      'نظام الدفع الكلي M xDrive مع وضعية الدفع الخلفي الخالص للدريفت',
      'نظام باورز آند ويلكنز الصوتي الماسي المحيطي بقوة 1,400 واط',
      'مكابح إم كربون سيراميكية مع باقة الكربون الخارجية الرياضية',
      'مصابيح ليزر بي إم دبليو الذكية بإضاءة زرقاء مميزة',
      'نظام تعليق إم الرياضي المتكيف مع مانع تدحرج الهيكل الإلكتروني',
      'عادم رياضي إم سبورت مع 4 فوهات مطلية بالكروم الأسود'
    ]
  }
];

export const initialMockBookings: Booking[] = [
  {
    _id: 'bok_demo_01',
    bookingReference: 'C2G-882910',
    vehicleId: 'veh_rr_spectre',
    vehicleName: 'Rolls-Royce Spectre',
    vehicleImage: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?auto=format&fit=crop&w=1600&q=85',
    userId: 'usr_client_01',
    customerName: 'Tariq Al-Mansoor',
    customerEmail: 'tariq.mansoor@vip.sa',
    customerPhone: '+966 55 987 6543',
    pickupLocation: 'Riyadh - King Khalid International Airport (Terminal 1-5 VIP)',
    returnLocation: 'Riyadh - King Khalid International Airport (Terminal 1-5 VIP)',
    pickupDate: '2026-09-12T10:00:00.000Z',
    returnDate: '2026-09-15T10:00:00.000Z',
    days: 3,
    baseDailyRate: 4800,
    baseTotal: 14400,
    addons: [{ id: 'chauffeur', name: 'Private Chauffeur Service', price: 900 }],
    addonsTotal: 900,
    promoCode: 'ROYAL20',
    discountAmount: 2880,
    vatRate: 0.15,
    vatAmount: 1863,
    depositAmount: 8000,
    totalAmount: 14283,
    paymentMethod: 'Credit Card (Apple Pay)',
    status: 'Confirmed',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    _id: 'bok_demo_02',
    bookingReference: 'C2G-741903',
    vehicleId: 'veh_porsche_911gt3',
    vehicleName: 'Porsche 911 GT3 RS',
    vehicleImage: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1600&q=85',
    userId: 'usr_client_01',
    customerName: 'Fahad Al-Saud',
    customerEmail: 'fahad@car2go.sa',
    customerPhone: '+966 50 123 4567',
    pickupLocation: 'Riyadh - Al Olaya Prestige Showroom',
    returnLocation: 'Riyadh - Al Olaya Prestige Showroom',
    pickupDate: '2026-09-18T14:00:00.000Z',
    returnDate: '2026-09-20T14:00:00.000Z',
    days: 2,
    baseDailyRate: 3900,
    baseTotal: 7800,
    addons: [{ id: 'delivery', name: 'Doorstep Enclosed Trailer Delivery', price: 500 }],
    addonsTotal: 500,
    discountAmount: 0,
    vatRate: 0.15,
    vatAmount: 1245,
    depositAmount: 6000,
    totalAmount: 9545,
    paymentMethod: 'Mada Direct',
    status: 'Confirmed',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString()
  }
];

